FROM python:3-slim as python
RUN apt-get update &&\
   apt-get install -y curl
RUN apt-get -y install gcc
ENV PYTHONUNBUFFERED=true
RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN POETRY_VIRTUALENVS_CREATE=false poetry install
COPY ./src/ /app/src/
EXPOSE 5000
ENV FLASK_APP=/app/src/webserver.py
ENTRYPOINT [ "flask"]
CMD [ "run", "--host", "0.0.0.0" ]
HEALTHCHECK --interval=5m --retries=2 CMD curl --fail http://localhost:5000/ping || exit 1
