name: Build webserver

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [closed]

env:
  NODE_VERSION: 20.x

jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: ./src/frontend/package.json

      - name: Install Yarn
        run: |
          cd ./src/frontend/
          npm install -g yarn

      - name: Yarn version Berry
        working-directory: ./src/frontend/
        run: yarn set version berry

      - name: Yarn init
        working-directory: ./src/frontend/
        run: yarn

      - name: Change directory and install dependencies
        working-directory: ./src/frontend/
        run: yarn install

      - name: Linting
        working-directory: ./src/frontend/
        run: yarn lint

      - name: Build
        working-directory: ./src/frontend/
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./src/frontend/build

  publish-docker-image:
    name: Publish Docker image
    needs: Build-Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: ./src/frontend/build

      - name: Set Docker build arguments
        run: |
          echo "ENABLE_FRONTEND=false" >> $GITHUB_ENV

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile.webserver
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/ktomi96/power_manager/webserver:latest
