name: Build webserver

# Controls when the workflow will run
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [closed]
        conditions:
      - ${{ github.event.pull_request.merged == true }}
      - ${{ github.event.pull_request.base.ref == 'master' }}
      - ${{ github.event.pull_request.draft == false }}

# permissions are needed if pushing to ghcr.io
jobs:
  publish-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:

      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.3.0
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
               # list of Docker images to use as base name for tags
          images: |
                 ghcr.io/ktomi96/power_manager/webserver
               # Docker tags based on the following events/attributes
          tags: |
           type=schedule
           type=ref,event=branch
           type=ref,event=pr
           type=semver,pattern={{version}}
           type=semver,pattern={{major}}.{{minor}}
           type=semver,pattern={{major}}
           type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.webserver
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}